### ISSUE TITLE
legacyImageFormats seems to be dropped

### ISSUE THREAD

**Issue by tigt** [helmetjs/feature-policy#5]
[Searching for that property name](https://www.google.com/search?q=%22legacyimageformats%22) only returns results from this project.

**Comment by EvanHahn** [comment]
Hmm, I see it documented here and supported by a few browsers: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/legacy-image-formats

Because of that I'm inclined to keep it. What do you think?

**Comment by tigt** [comment]
Oh, derp. I searched for the camelCase version; no wonder it didn't come up.

**Comment by EvanHahn** [comment]
No worries—thanks for keeping an eye out!
